/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.47
 * Generated at: 2018-08-08 11:23:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Cmpny_005fExp_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Techtronixs</title>\r\n");
      out.write("<script>\r\n");
      out.write("\tfunction sum() {\r\n");
      out.write("\t\tvar Tea = document.getElementById('Tea').value;\r\n");
      out.write("\t\tvar Salary = document.getElementById('Salary').value;\r\n");
      out.write("\t\tvar Diesel = document.getElementById('Diesel').value;\r\n");
      out.write("\t\tvar Advance = document.getElementById('Advance').value;\r\n");
      out.write("\t\tvar Others = document.getElementById('Others').value;\r\n");
      out.write("\t\tvar Sales = document.getElementById('Sales').value;\r\n");
      out.write("\t\tvar OpeningAmount = document.getElementById('OpeningAmount').value;\r\n");
      out.write("\t\tvar result = parseInt(Tea) + parseInt(Salary)+parseInt(Diesel)+parseInt(Advance)+parseInt(Others);\r\n");
      out.write("\t\tvar dif =parseInt(Sales)- (parseInt(OpeningAmount)+parseInt(result));\r\n");
      out.write("\t\tif (!isNaN(result)) {\r\n");
      out.write("\t\t\tdocument.getElementById('Expenses').value = result;\r\n");
      out.write("\t\t\tdocument.getElementById('TotalSales').value = dif;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("\t<form action=\"Cmpny_Exp_submit\" method=\"post\">\r\n");
      out.write("\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t<label for=\"email\">OpeningAmount:</label> <input type=\"text\"\r\n");
      out.write("\t\t\t\tclass=\"form-control\" id=\"OpeningAmount\"\r\n");
      out.write("\t\t\t\tplaceholder=\"Enter OpeningAmount\" name=\"OpeningAmount\" required>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t<label for=\"pwd\">Expenses:</label> <input type=\"text\"\r\n");
      out.write("\t\t\t\tclass=\"form-control\" id=\"Expenses\" placeholder=\"Enter Expenses\"\r\n");
      out.write("\t\t\t\tname=\"Expenses\" readonly required>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<label for=\"pwd\">Tea:</label> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\tclass=\"form-control\" id=\"Tea\" placeholder=\"Enter Tea amount\"\r\n");
      out.write("\t\t\t\t\tname=\"Tea\" onkeyup=\"sum();\" required>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<label for=\"pwd\">Salary:</label> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\tclass=\"form-control\" id=\"Salary\" placeholder=\"Enter Salary\"\r\n");
      out.write("\t\t\t\t\tname=\"Salary\" onkeyup=\"sum();\" required>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<label for=\"pwd\">Diesel :</label> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\tclass=\"form-control\" id=\"Diesel\" placeholder=\"Enter Diesel\"\r\n");
      out.write("\t\t\t\t\tname=\"Diesel\" onkeyup=\"sum();\" required>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<label for=\"pwd\">Advance :</label> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\tclass=\"form-control\" id=\"Advance\" placeholder=\"Enter Advance\"\r\n");
      out.write("\t\t\t\t\tname=\"Advance\" onkeyup=\"sum();\" required>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<label for=\"pwd\">Others:</label> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\tclass=\"form-control\" id=\"Others\" placeholder=\"Enter Others\"\r\n");
      out.write("\t\t\t\t\tname=\"Others\" onkeyup=\"sum();\" required>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<label for=\"pwd\">Sales:</label> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\tclass=\"form-control\" id=\"Sales\" placeholder=\"Enter Sales\"\r\n");
      out.write("\t\t\t\t\tname=\"Sales\" onkeyup=\"sum();\" required>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<label for=\"pwd\">TotalSales:</label> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\tclass=\"form-control\" id=\"TotalSales\" placeholder=\"Enter TotalSales\"\r\n");
      out.write("\t\t\t\t\tname=\"TotalSales\" readonly required>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"col-sm-12 form-group\">\r\n");
      out.write("\t\t\t<center>\r\n");
      out.write("\t\t\t\t<button type=\"submit\" class=\"btn btn-lg btn-info\">Submit</button>\r\n");
      out.write("\t\t\t\t<button type=\"reset\" class=\"btn btn-lg btn-info\">Clear</button>\r\n");
      out.write("\t\t\t</center>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</form>\r\n");
      out.write("\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
