/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.47
 * Generated at: 2018-08-05 08:40:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class submit_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Techtronixs</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("@media print {\r\n");
      out.write("\t.bg-primary {\r\n");
      out.write("\t\tbackground-color: #6ee2ef !important;\r\n");
      out.write("\t\t \r\n");
      out.write("        \r\n");
      out.write("\t}\r\n");
      out.write("\t.primary {\r\n");
      out.write("\t\tbackground-color: #86efe8 !important;\r\n");
      out.write("\t\t color: yellow !important;\r\n");
      out.write("        \r\n");
      out.write("\t}\r\n");
      out.write("\t.table td {\r\n");
      out.write("\t\tbackground-color: transparent !important;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("p.thicker {\r\n");
      out.write("\tfont-weight: 900;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h2.thicker {\r\n");
      out.write("\tfont-weight: 900;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h3.thicker {\r\n");
      out.write("\tfont-weight: 900;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h5.thicker {\r\n");
      out.write("\tfont-weight: 900;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h4.thicker {\r\n");
      out.write("\tfont-weight: 900;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h4.font {\r\n");
      out.write("\tfont-size: 25px;\r\n");
      out.write("\tfont-weight: 900;\r\n");
      out.write("\tfont-color: red;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h4.abi {\r\n");
      out.write("\tfont-size: 40px;\r\n");
      out.write("\tfont-weight: 900;\r\n");
      out.write("\tfont-color: red;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "BillHeader.jsp", out, false);
      out.write("\r\n");
      out.write("\t<div class=\"bg-primary\" class=\"container\">\r\n");
      out.write("\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t<div class=\"col-sm-2 form-inline\">\r\n");
      out.write("\t\t\t\t<img\r\n");
      out.write("\t\t\t\t\tsrc=\"http://www.wordzz.com/wp-content/uploads/2017/04/Lakshmi.png\"\r\n");
      out.write("\t\t\t\t\tclass=\"img-responsive\" width=\"100\" height=\"200\">\r\n");
      out.write("\t\t\t\t<h4 class=\"thicker\">AGT</h4>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-sm-8 form-inline\">\r\n");
      out.write("\t\t\t\t<h2 class=\"thicker\" align=\"center\">SRI ANANDA</h2>\r\n");
      out.write("\t\t\t\t<h4 class=\"thicker\" align=\"center\">Gold & Silver Testings</h4>\r\n");
      out.write("\t\t\t\t<h4 class=\"thicker\" align=\"center\">Computerized X-Ray Point\r\n");
      out.write("\t\t\t\t\tGold Assay Report</h4>\r\n");
      out.write("\t\t\t\t<h4 class=\"thicker\" align=\"center\">101/1 Dhurairaj complex,Main\r\n");
      out.write("\t\t\t\t\tRoad,Dindigul</h4>\r\n");
      out.write("\t\t\t\t<h4 class=\"thicker\" align=\"center\">cell:-9965976916</h4>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"form-group\" class=\"col-sm-2 form-inline\">\r\n");
      out.write("\t\t\t\t<img\r\n");
      out.write("\t\t\t\t\tsrc=\"http://www.tirutanigaimurugan.tnhrce.in/images/rajaalangaram.png\"\r\n");
      out.write("\t\t\t\t\tclass=\"img-responsive\" width=\"100\" height=\"200\">\r\n");
      out.write("\t\t\t\t<h4 class=\"thicker\" align=\"left\">AGT</h4>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<table class=\"table\"\r\n");
      out.write("\t\tclass=\"table table-striped table-bordered dt-responsive nowrap\"\r\n");
      out.write("\t\tclass=\"thicker\">\r\n");
      out.write("\r\n");
      out.write("\t\t<tbody>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-2 form-inline\">\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"thicker\">TOKEN_NO</h4>\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"thicker\">DATE</h4>\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"thicker\">NAME</h4>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-3 form-inline\" align=\"left\">\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"thicker\">:- ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${u.getUserid() }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h4>\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"thicker\">:- ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${u.getDate() }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h4>\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"thicker\">:- ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${u.getName() }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h4>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-2 form-inline\">\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"thicker\">WEIGHT</h4>\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"thicker\">SAMPLE_TYPE</h4>\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"thicker\">KARAT</h4>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-2 form-inline\" align=\"left\">\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"thicker\">:- ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${u.getWeight() }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h4>\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"thicker\">:- ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${u.getSample_type() }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h4>\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"thicker\">:- ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${u.getKarat() }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h4>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-2 form-inline\" >\r\n");
      out.write("\t\t\t\t\t\t<div class=\"primary\" style=\"border: 5px solid black\">\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"font\"  class=\"primary\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\tGOLD\r\n");
      out.write("\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t<h4  class=\"abi\"  class=\"primary\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${u.getGold() }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" \r\n");
      out.write("\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-2 form-inline\">\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"thicker\">SILVER</h4>\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"thicker\">COPPER</h4>\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"thicker\">ZINC</h4>\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"thicker\">KDM</h4>\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"thicker\">NICKEL</h4>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-4 form-inline\" align=\"left\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"thicker\">:- ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${u.getSilver()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h4>\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"thicker\">:- ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${u.getCopper() }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h4>\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"thicker\">:- ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${u.getZinc() }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h4>\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"thicker\">:- ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${u.getKDM() }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h4>\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"thicker\">:- ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${u.getNickel() }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h4>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-2 form-inline\">\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"thicker\">IRIDIUM</h4>\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"thicker\">TIN</h4>\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"thicker\">IRON</h4>\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"thicker\">PLATINUM</h4>\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"thicker\">OTHERS</h4>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-4 form-inline\" align=\"left\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"thicker\">:- ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${u.getIridium() }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h4>\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"thicker\">:- ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${u.getTin() }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h4>\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"thicker\">:- ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${u.getIron() }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h4>\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"thicker\">:- ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${u.getPlatinum() }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h4>\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"thicker\">:- ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${u.getOthers() }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h4>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-6 form-inline\">\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"thicker\">Remarks:-</h4>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-6 form-inline\">\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"thicker\">For SRI ANANDA:-</h4>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</tbody>\r\n");
      out.write("\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<div class=\"p-3 mb-2 bg-primary text-white\" class=\"container\"\r\n");
      out.write("\t\tclass=\"thicker\">\r\n");
      out.write("\t\t\t<h5 class=\"bg-primary\"   class=\"thicker\" >ASSAYING METHOD : FIRE ASSAY METHOD AS PER\r\n");
      out.write("\t\t\t\tNATIONAL & INTERNATIONAL STANDARDS /NOTE : TEST REPORT RELATES ONLY TO THE ITEM\r\n");
      out.write("\t\t\t\tTESTED </h5>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"col-sm-12 form-group\">\r\n");
      out.write("\t\t<center>\r\n");
      out.write("\t\t\t<input class=\"btn btn-lg btn-info\" class=\"text-center\"\r\n");
      out.write("\t\t\t\tid=\"printpagebutton\" type=\"button\" value=\"Print\"\r\n");
      out.write("\t\t\t\tonclick=\"printpage()\" />\r\n");
      out.write("\t\t</center>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tfunction printpage() {\r\n");
      out.write("\t\t\tvar printButton = document.getElementById(\"printpagebutton\");\r\n");
      out.write("\t\t\tprintButton.style.visibility = 'hidden';\r\n");
      out.write("\t\t\twindow.print()\r\n");
      out.write("\t\t\tprintButton.style.visibility = 'visible';\r\n");
      out.write("\t\t\twindow.location.href = \"index\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
